site_name: Conatus Standards
site_url: https://github.com/conatussw/django-standards

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - About: about.md
  - References: references.md

theme:
  name: 'material'
