# Generated by Django 5.0.4 on 2024-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('featured_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
    ]
